title: "Plotting the price and availability of specified housing in specified municipally"
data_source_1:
  title: "Försålda småhus efter region (kommun, län, riket) och fastighetstyp. År 1981 - 2024"
  description: "Assessed value for small house, region and year."
  url: |
  "https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__BO__BO0501__BO0501B/FastprisSHRegionAr/"
data_source_2:
  title: "Antal lägenheter efter region, hustyp och upplåtelseform (inklusive specialbostäder). År 1990 - 2024"
  description: "Number of respective house type, per municipality."
  url: |
  "https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__BO__BO0104__BO0104D/BO0104T04/"
data_source_3:
  title: "Bostadsstatistik direkt från fastighetsmäklarnas affärssystem"
  description: "Yearly statistics of commondiums, created using the web scraper"
  url: |
  "https://www.maklarstatistik.se/"